### PR TITLE
ApplicationData: Unpackaged support

### LINKED ISSUE #2639: Microsoft.Storage.ApplicationData
### Describe the bug

# Proposal: Microsoft.Storage.ApplicationData

## Summary
Provide a modern enhanced version of [Windows.Storage.ApplicationData](https://docs.microsoft.com/uwp/api/windows.storage.applicationdata?view=winrt-22621) and [Windows.Management.Core.ApplicationDataManager](https://docs.microsoft.com/uwp/api/Windows.Management.Core.ApplicationDataManager?view=winrt-22621)

Microsoft-internal task [NNN](https://task.ms/NNN)

## Rationale
* `Windows.Storage.ApplicationData.Current` only works fir you have package identity AND running in AppContainer
* `Windows.Management.Core.ApplicationDataManager.CreateForPackageFamily` is equivalent but requires you have package identity AND running MediumIL or higher
* Unpackaged apps have long been advised to use `%LOCALAPPDATA%\publisher\product`, `%LOCALAPPDATA%\Temp` and `HKCU\SOFTWARE\publisher\product` but ApplicationData doesn't support that
* `Windows.Storage.ApplicationData` has several deprecated and obsolete features (e.g. [.RoamingFolder](https://docs.microsoft.com/uwp/api/windows.storage.applicationdata.roamingfolder?view=winrt-22621))
* `ApplicationData.*Folder` only provide access to the filesystem via `StorageFolder`. There's no way to get their `.Path` without going thrug a `StorageFolder` incurring significant performance overhead
* `ApplicationData` has async methods which should be available synchronously e.g. `ClearAsync()` should offer `Clear() as a synchronous variant (or replacement?)

Windows App SDK can and should provide a modern revision of the `ApplicationData` API, addressing the issues above.

## Scope
| Capability | Priority |
| :---------- | :------- |
| APIs available to packaged and unpackaged applications | Must |
| APIs offer filesystem access without requiring use of StorageFolder | Must |
| WinRT API | Must |

## Important Notes

Here's a sketch of the general shape of the API to express the intent of the ask. The actual API when designed/spec'd/reviewed/approved may differ.

### WinRT API
Microsoft.Storage.ApplicationData.idl
```c# (closest to midl3)
namespace Microsoft.Storage.ApplicationData
{
[contract(ApplicationData, 1)]
enum ApplicationDataLocality
{
    Local = 0,
    LocalCache = 3,
    SharedLocal = 4,
    Temporary = 2,
}

[contract(ApplicationData, 1)]
runtimeclass ApplicationData
{
    /// Return an ApplicationData object if the current process has package identity
    /// NOTE: This is equivalent to `ApplicationData.ForPackageFamily(Windows.ApplicationModel.Package.Current.Id.FamilyName)`
    static ApplicationData GetDefault();

    /// NOTE: Requires MediumIL (or higher) if the process lacks package identity.
    /// NOTE: Requires MediumIL (or higher) if the process has package identity but different from the packageFamilyName parameer.
    /// NOTE: GetForPackageFamily(Windows.ApplicationModel.Package.Current.Id.FamilyName) is equivalent to GetDefault()
    static ApplicationData GetForPackageFamily(String packageFamilyName);

    /// NOTE: Requires admin privilege if user != current user
    /// NOTE: GetForUser(Window.System.User.GetDefault) is equivalent to GetDefault()
    static ApplicationData GetForUser(Windows.System.User user);

    /// NOTE: Requires admin privilege if user != current user
    /// NOTE: GetForUser(Window.System.User.GetDefault, packageFamilyName) is equivalent to GetForPackageFamily(packageFamilyName)
    static ApplicationData GetForUser(Windows.System.User user, String packageFamilyName);

    StorageFolder LocalCacheFolder;
    StorageFolder LocalFolder;
    StorageFolder TemporaryFolder;
    StorageFolder SharedLocalFolder;    //NOTE: Returns NULL if process lacks package identity

    String LocalCachePath;
    String LocalPath;
    String TemporaryPath;
    String SharedLocalPath; //NOTE: Returns NULL if process lacks package identity

    ApplicationDataContainer LocalSettings;

    void Clear();
    void Clear(ApplicationDataLocality locality);

    AsyncAction ClearAsync();
    AsyncAction ClearAsync(ApplicationDataLocality locality);
}

## Open Questions

Q: Is there an unpackaged equivalent to [GetPublisherCacheFolder()](https://docs.microsoft.com/uwp/api/windows.storage.applicationdata.getpublishercachefolder)?

### Steps to reproduce the bug

DELETEME

### Expected behavior

DELETEME

### Screenshots

_No response_

### NuGet package version

_No response_

### Packaging type

_No response_

### Windows version

_No response_

### IDE

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DrusTheAxe**
Provide ApplicationData Unpackaged support

#close #2639

### CODE REVIEW

File: dev/ApplicationData/UnpackagedApplicationData.cpp [hunk 1]
```diff
@@ -0,0 +1,276 @@
...
+        auto logTelemetryContinuation{ logTelemetry.ContinueOnCurrentThread() };
+
+        // Clear the path
+        if (!localityPath.empty())
+        {
+            std::filesystem::path path{ localityPath.c_str() };
+            if (_PathExists(path))
+            {
+                const auto options{ wil::RemoveDirectoryOptions::KeepRootDirectory | wil::RemoveDirectoryOptions::RemoveReadOnly };
+                THROW_IF_FAILED(wil::RemoveDirectoryRecursiveNoThrow(path.c_str(), options));
```
Comment (letao-msft) [inline dev/ApplicationData/UnpackagedApplicationData.cpp:201]: >RemoveDirectoryRecursiveNoThrow [](http://example.com/codeflow?start=37&length=31)

Copilot feedback:

UnpackagedApplicationData.cpp — publisher and product are only checked for emptiness, then directly interpolated into filesystem paths:

 path /= m_publisher.c_str();  // No validation!
 path /= m_product.c_str();

An attacker can pass "..\\..\\Windows\\System32" to escape the intended directory. ClearAsync then calls RemoveDirectoryRecursiveNoThrow on these paths — enabling arbitrary directory deletion.

Fix: Reject path separators (\, /), .., and : in both parameters. A whitelist of safe characters is safest. #Closed

File: dev/ApplicationData/UnpackagedApplicationData.cpp [hunk 2]
```diff
@@ -0,0 +1,276 @@
...
+            }
+        }
+
+        // Clear the settings (if necessary)
+        if (locality == winrt::Microsoft::Windows::Storage::ApplicationDataLocality::Local)
+        {
+            wil::unique_hkey currentUserKey;
+            THROW_IF_WIN32_ERROR(::RegOpenCurrentUser(KEY_READ | KEY_WRITE, currentUserKey.put()));
+            auto subKey{ std::format(L"SOFTWARE\\{}\\{}", publisher, product) };
+            const auto hr{ HRESULT_FROM_WIN32(::RegDeleteTreeW(currentUserKey.get(), subKey.c_str())) };
```
Comment (letao-msft) [inline dev/ApplicationData/UnpackagedApplicationData.cpp:211]: >RegDeleteTreeW [](http://example.com/codeflow?start=48&length=14)

Copilot feedback:

 Same unsanitized strings are interpolated into registry paths:

   auto subKey{ std::format(L"SOFTWARE\\{}\\{}", m_publisher, m_product) };

  ClearAsync calls RegDeleteTreeW on the result — enabling arbitrary HKCU registry key deletion.

  Fix: Same validation as above — reject backslashes and path-traversal patterns.
 #Closed

File: dev/ApplicationData/UnpackagedApplicationDataContainer.cpp [hunk 3]
```diff
@@ -0,0 +1,904 @@
...
+            auto subContainer{ std::make_shared<UnpackagedApplicationDataContainer>(std::move(subKey), name, m_locality) };
+            return winrt::make<winrt::Microsoft::Windows::Storage::implementation::ApplicationDataContainer>(subContainer);
+        }
+    }
+
+    void UnpackagedApplicationDataContainer::DeleteContainer(winrt::hstring const& name)
+    {
+        _VerifyNotClosed();
+
+        const auto hr{ HRESULT_FROM_WIN32(::RegDeleteTreeW(m_key.get(), name.c_str())) };
```
Comment (letao-msft) [inline dev/ApplicationData/UnpackagedApplicationDataContainer.cpp:899]: >RegDeleteTreeW [](http://example.com/codeflow?start=44&length=14)

Copilot feedback:

CreateContainer/DeleteContainer pass name directly as a registry subkey:

 auto subKey{ wil::reg::create_shared_key(m_key.get(), name.c_str(), ...) };
 RegDeleteTreeW(m_key.get(), name.c_str());

Names like "..\\OtherKey" escape the container scope. Fix: Validate container names contain no backslashes. #Closed

File: dev/ApplicationData/UnpackagedApplicationData.cpp [hunk 4]
```diff
@@ -0,0 +1,276 @@
...
+            localityPath = TemporaryPath();
+            break;
+        }
+        case winrt::Microsoft::Windows::Storage::ApplicationDataLocality::Machine:
+        {
+            localityPath = MachinePath();
+            break;
+        }
+        default:
+            THROW_HR_MSG(E_INVALIDARG, "%d", static_cast<int>(locality));
```
Comment (letao-msft) [inline dev/ApplicationData/UnpackagedApplicationData.cpp]: >E_INVALIDARG [](http://example.com/codeflow?start=25&length=12)

Copilot feedback:

inconsistent error codes for unsupported localities

 ClearAsync(LocalCache)     → E_INVALIDARG  (default case in switch)
 LocalCachePath()           → hresult_not_implemented

 ClearAsync(SharedLocal)    → E_INVALIDARG  (default case in switch)
 SharedLocalPath()          → hresult_not_implemented

A caller gets different error types for the same conceptual "not supported" scenario depending on which method they call. Consider adding explicit cases:

 case ApplicationDataLocality::LocalCache:
 case ApplicationDataLocality::SharedLocal:
     throw winrt::hresult_not_implemented(); #Closed

File: dev/ApplicationData/UnpackagedApplicationDataContainer.cpp [hunk 5]
```diff
@@ -0,0 +1,904 @@
...
+            case REG_MULTI_SZ:
+            {
+                std::vector<BYTE> buffer(dataSize);
+                THROW_IF_WIN32_ERROR(::RegQueryValueExW(key, valueName, nullptr, nullptr, buffer.data(), &dataSize));
+                auto* p{ reinterpret_cast<const wchar_t*>(buffer.data()) };
+                auto* end{ reinterpret_cast<const wchar_t*>(buffer.data() + dataSize) };
+                std::vector<winrt::hstring> strings;
+                while (p < end && *p != L'\0')
+                {
+                    winrt::hstring str{ p };
```
Comment (letao-msft) [inline dev/ApplicationData/UnpackagedApplicationDataContainer.cpp]: >p [](http://example.com/codeflow?start=40&length=1)

Bounds check: if the data is corrupt or tampered such that buffer doesn't end with a null terminator, then hstring{p} might read past the end of the buffer.  This code only checks if p starts before the end of the buffer, but doesn't guarantee the resulting string will end before the end of the buffer.

Suggested fix:
```
 while (p < end && *p != L'\0')
 {
     auto len{ wcsnlen(p, static_cast<size_t>(end - p)) };
     winrt::hstring str{ p, static_cast<winrt::hstring::size_type>(len) };
     strings.push_back(str);
     p += len + 1;
 }
``` #Closed

File: dev/ApplicationData/UnpackagedApplicationDataContainer.cpp [hunk 6]
```diff
@@ -0,0 +1,904 @@
...
+            {
+                auto value{ wil::reg::get_value_qword(key, valueName) };
+                return winrt::box_value(value);
+            }
+            case REG_MULTI_SZ:
+            {
+                std::vector<BYTE> buffer(dataSize);
+                THROW_IF_WIN32_ERROR(::RegQueryValueExW(key, valueName, nullptr, nullptr, buffer.data(), &dataSize));
+                auto* p{ reinterpret_cast<const wchar_t*>(buffer.data()) };
+                auto* end{ reinterpret_cast<const wchar_t*>(buffer.data() + dataSize) };
```
Comment (letao-msft) [inline dev/ApplicationData/UnpackagedApplicationDataContainer.cpp:133]: If the registry contains corrupt data where dataSize is odd, end points to the middle of a wchar_t. Check to be safe:
```
 THROW_HR_IF(E_UNEXPECTED, dataSize % sizeof(wchar_t) != 0);
``` #Closed

File: test/ApplicationData/UnpackagedApplicationDataTests.cpp [hunk 7]
```diff
@@ -0,0 +1,1104 @@
...
+            values.Insert(L"String", winrt::box_value(L"Updated"));
+            VERIFY_ARE_EQUAL(L"Updated", winrt::unbox_value<winrt::hstring>(values.Lookup(L"String")));
+
+            // Verify count
+            VERIFY_ARE_EQUAL(20u, values.Size());
+
+            values.Clear();
+        }
+
+        TEST_METHOD(Values_ArrayTypes)
```
Comment (letao-msft) [inline test/ApplicationData/UnpackagedApplicationDataTests.cpp:781]: >Values_ArrayTypes [](http://example.com/codeflow?start=20&length=17)

Consider adding test cases where the array size and/or data size is 0, wherever applicable. #Closed

File: dev/ApplicationData/UnpackagedApplicationData.h [hunk 8]
```diff
@@ -0,0 +1,45 @@
...
+    private:
+        void _VerifyNotClosed();
+        static std::filesystem::path _MachinePath(winrt::hstring const& publisher, winrt::hstring const& product);
+        static bool _PathExists(std::filesystem::path const& path);
+
+    private:
+        winrt::hstring m_publisher;
+        winrt::hstring m_product;
+        winrt::hstring m_localPath;
+        std::filesystem::path m_machinePath;
```
Comment (letao-msft) [inline dev/ApplicationData/UnpackagedApplicationData.h]: >m_machinePath [](http://example.com/codeflow?start=30&length=13)

This is never used #Closed

File: dev/ApplicationData/UnpackagedApplicationDataContainer.cpp [hunk 9]
```diff
@@ -0,0 +1,904 @@
...
+                for (const auto& valueData : wil::make_range(wil::reg::value_iterator{ m_key.get() }, wil::reg::value_iterator{}))
+                {
+                    try
+                    {
+                        auto value{ ReadRegistryValue(m_key.get(), valueData.name.c_str()) };
+                        snapshot.Insert(winrt::hstring{ valueData.name }, value);
+                    }
+                    catch (...)
+                    {
+                        // Skip values that cannot be read
```
Comment (letao-msft) [inline dev/ApplicationData/UnpackagedApplicationDataContainer.cpp:679]: Add LOG_CAUGHT_EXCEPTION() for diagnosability #Closed

File: dev/ApplicationData/UnpackagedApplicationDataContainer.cpp [hunk 10]
```diff
@@ -0,0 +1,904 @@
...
+                {
+                    try
+                    {
+                        auto value{ ReadRegistryValue(m_key.get(), valueData.name.c_str()) };
+                        items.push_back(winrt::Windows::Foundation::Collections::IKeyValuePair<winrt::hstring, winrt::Windows::Foundation::IInspectable>{
+                            winrt::make<KeyValuePair>(winrt::hstring{ valueData.name }, value) });
+                    }
+                    catch (...)
+                    {
+                        // Skip values that cannot be read
```
Comment (letao-msft) [inline dev/ApplicationData/UnpackagedApplicationDataContainer.cpp:748]: Add LOG_CAUGHT_EXCEPTION() for diagnosability #Closed

File: dev/ApplicationData/UnpackagedApplicationData.cpp (hunk 1 above)
Comment (DrusTheAxe) [reply dev/ApplicationData/UnpackagedApplicationData.cpp:201]: Control characters, not-printable characters, whitespace (CR, LF, vertical tab, ...) and other Unicode complexities. And unnecessary. Restricting to ASCII alphanumeric, DOT, DASH, UNDERSCORE and SPACE to cover the need, plus string restrictions (can't be "..", "lpt1", etc or start with "lpt1.") -- similar to Package Identity restrictions (for similar reasons)

File: dev/ApplicationData/UnpackagedApplicationDataContainer.cpp (hunk 6 above)
Comment (DrusTheAxe) [reply dev/ApplicationData/UnpackagedApplicationDataContainer.cpp:133]: The irony is the code AI's complaining about was written by AI :P

File: test/ApplicationData/UnpackagedApplicationDataTests.cpp (hunk 7 above)
Comment (DrusTheAxe) [reply test/ApplicationData/UnpackagedApplicationDataTests.cpp:781]: Largely blocked by PropertyValue::Create*Array() rejecting such things

(and almost entirely impossible because WinRT projections take `blah[]` so unless you can make a zero-length array...)

File: dev/ApplicationData/UnpackagedApplicationDataContainer.cpp (hunk 9 above)
Comment (DrusTheAxe) [reply dev/ApplicationData/UnpackagedApplicationDataContainer.cpp:679]: I didn't know about that macro. Neat

File: dev/ApplicationData/UnpackagedApplicationData.cpp [hunk 11]
```diff
@@ -0,0 +1,273 @@
...
+#include "UnpackagedApplicationDataContainer.h"
+
+#include "ApplicationDataTelemetry.h"
+
+namespace Microsoft::Windows::Storage
+{
+    UnpackagedApplicationData::UnpackagedApplicationData(winrt::hstring const& publisher, winrt::hstring const& product) :
+        m_publisher(publisher),
+        m_product(product),
+        m_localPath()
```
Comment (letao-msft) [inline dev/ApplicationData/UnpackagedApplicationData.cpp]: >m_localPath [](http://example.com/codeflow?start=8&length=11)

Why initialize m_localPath but not m_temporaryPath?
Similarly in Close(), why clear m_localPath but not m_temporaryPath? #Closed

File: dev/ApplicationData/UnpackagedApplicationDataContainer.cpp (hunk 6 above)
Comment (letao-msft) [reply dev/ApplicationData/UnpackagedApplicationDataContainer.cpp:133]: Clearly, it didn't check its work :p

File: dev/ApplicationData/UnpackagedApplicationDataContainer.cpp (hunk 9 above)
Comment (letao-msft) [reply dev/ApplicationData/UnpackagedApplicationDataContainer.cpp:679]: Neither did I, but the AI overlords did.

File: dev/ApplicationData/UnpackagedApplicationDataContainer.cpp [hunk 12]
```diff
@@ -0,0 +1,928 @@
...
+        THROW_HR_IF_NULL(RO_E_CLOSED, m_key);
+    }
+
+    void UnpackagedApplicationDataContainer::_VerifyContainerName(winrt::hstring const& name)
+    {
+        THROW_HR_IF_MSG(E_INVALIDARG, name.empty(), "Container name not valid (%ls)", name.c_str());
+
+        for (PCWSTR s = name.c_str(); *s != L'\0'; ++s)
+        {
+            THROW_HR_IF_MSG(E_INVALIDARG, *s == L'\\', "Container name not valid (%ls)", name.c_str());
```
Comment (letao-msft) [inline dev/ApplicationData/UnpackagedApplicationDataContainer.cpp:924]: Is this necessary?  contains_prohibited_character below would already reject '\\' in the string #Closed

**Review by letao-msft — DISMISSED** [review]
:shipit:

File: dev/ApplicationData/UnpackagedApplicationData.cpp (hunk 11 above)
Comment (DrusTheAxe) [reply dev/ApplicationData/UnpackagedApplicationData.cpp]: Technically it's initialized because ctor and not listed, but yeah better to list both or neither (I prefer to list all, easier to avoid future mistakes)

Comment (DrusTheAxe) [reply dev/ApplicationData/UnpackagedApplicationData.cpp]: As for Close(), for the same reason...er, I added temp after and forgot to init or clear it? :P

File: dev/ApplicationData/UnpackagedApplicationDataContainer.cpp (hunk 12 above)
Comment (DrusTheAxe) [reply dev/ApplicationData/UnpackagedApplicationDataContainer.cpp:924]: Good catch. Container name validation rules are simpler -- can't be empty, can't contain backslash and can't be >255 chars (max regkey length).

Product+Publisher need more restrictions because filesystem, thus no ">", "lpt1", etc

Fixed the validation logic

Comment (letao-msft) [reply dev/ApplicationData/UnpackagedApplicationDataContainer.cpp:924]: "." and ".." still shouldn't be allowed here, right?
I think the validation in your previous iteration was fine (only the '\\' check was redundant).  You just needed:
- Max length 255
- !contains_prohibited_character
- Not "." or ".."

**Review by letao-msft — DISMISSED** [review]
:shipit:

**Review by letao-msft — APPROVED** [review]
:shipit:
