### PR TITLE
Reapply "Fix: getting activity context by reference (#6000)" (#6004)

### LINKED ISSUE #6016: Activity Context object is not being updated in DeploymentManager::DeployPackages method
On the `DeployPackages` method of the `DeploymentManager`, the `activityContext` variable [is being initialized as a copy](https://github.com/microsoft/WindowsAppSDK/blob/main/dev/Deployment/DeploymentManager.cpp#L577) and not as a reference. This results in the global context object not being updated after the start of this method's execution. Therefore, the telemetry data stops being relevant as every possible error or crash the originates after this point will be reported as in the license installation stage, which was the last stage that properly updated the correct object.

### PR DESCRIPTION
**Pull request by guimafelipe**
This reverts commit 60ea859378b7e9d1427c36da8b8a7dc50fa98cbf.

Fixes #6016 

The activity context global variable was not being get by reference, we were getting a copy of it instead. This creates an issue in telemetry collection as in the deployment stage, it was never actually setting the data on the global variable, but into a local copy of it inside the method's scope.

This makes any error originated inside the deployment method to be reported as an error in the installation phase with the singleton license, making it hard to track down the possible error origin.

Added to the previous change, the Activity Context class was changed to be a proper singleton, with private constructor and deleting the copy constructor. The global context variable was moved to inside the class scope.

TO-DO: Add unit tests to check the activity behavior after the refactoring of the deployment manager flow.

A microsoft employee must use /azp run to validate using the pipelines below.

WARNING:
Comments made by azure-pipelines bot maybe inaccurate.
Please see pipeline link to verify that the build is being ran.

For status checks on the main branch, please use TransportPackage-Foundation-PR
(https://microsoft.visualstudio.com/ProjectReunion/_build?definitionId=81063&_a=summary)
and run the build against your PR branch with the default parameters.

### CODE REVIEW

File: dev/Deployment/DeploymentManager.cpp [hunk 1]
```diff
@@ -574,7 +574,7 @@ namespace winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::implem
 
     HRESULT DeploymentManager::DeployPackages(const std::wstring& frameworkPackageFullName, const bool forceDeployment)
     {
-        auto initializeActivity{ ::WindowsAppRuntime::Deployment::Activity::Context::Get() };
+        auto& initializeActivity{ ::WindowsAppRuntime::Deployment::Activity::Context::Get() };
```
Comment (Scottj1s) [inline dev/Deployment/DeploymentManager.cpp:577]: you might also consider this to prevent the original situation (it's a bit odd that Get returns a ref):

`Context(const Context&) = delete;`

could also make it explicit, but doesn't appear to be any need for it.

Comment (guimafelipe) [reply dev/Deployment/DeploymentManager.cpp:577]: The better approach in my opinion is to pass it as a parameter to the function or method (which is what I did in the refactor PR).

This change here is following the pattern on what is in other parts of the repository that does the same thing (for example, the installer code).

**Review by Scottj1s — APPROVED** [review]

**Comment by guimafelipe** [comment]
> delete the copy ctor

I decided to keep the `Context()` constructor public for two reasons:
- It is less change to what the code is right now
- It is desirable for writing unit tests to be able to create the context manually, passing to functions and then checking it state.
