### PR TITLE
Bug Fix #5605 - 1.8 exp4: App crashes at DeploymentManager.Initialize();

### LINKED ISSUE #5605: 1.8 exp4: App crashes at `DeploymentManager.Initialize();`
### Describe the bug

With Windows App SDK 1.8 experimental 4, when calling `DeploymentManager.Initialize();` the app crashes fatally.

```
 	KernelBase.dll!RaiseFailFastException()	Unknown
 	Microsoft.WindowsAppRuntime.dll!wil::details::WilDynamicLoadRaiseFailFastException(_EXCEPTION_RECORD * er, _CONTEXT * cr, unsigned long flags) Line 2620	C++
 	Microsoft.WindowsAppRuntime.dll!wil::details::WilRaiseFailFastException(_EXCEPTION_RECORD * er, _CONTEXT * flags, unsigned long cr) Line 2553	C++
 	Microsoft.WindowsAppRuntime.dll!wil::details::WilFailFast(const wil::FailureInfo & failure) Line 4514	C++
 	[Inline Frame] Microsoft.WindowsAppRuntime.dll!wil::ActivityBase<WindowsAppRuntimeDeployment_TraceLogger,1,140737488355328,5,16777216,_TlgReflectorTag_Param0IsProviderType>::ActivityData<WindowsAppRuntimeDeployment_TraceLogger,_TlgReflectorTag_Param0IsProviderType>::SetStopResult(HRESULT) Line 1241	C++
 	[Inline Frame] Microsoft.WindowsAppRuntime.dll!wil::ActivityBase<WindowsAppRuntimeDeployment_TraceLogger,1,140737488355328,5,16777216,_TlgReflectorTag_Param0IsProviderType>::SetStopResult(HRESULT) Line 1053	C++
 	Microsoft.WindowsAppRuntime.dll!WindowsAppRuntimeDeployment_TraceLogger::Initialize::StopWithResult(HRESULT hresult, unsigned int failureType, const char * failureFile, unsigned int failureLineNumber, const wchar_t * failureMessage, const char * failureModule, unsigned int preInitializeStatus, unsigned int installStage, const wchar_t * currentResourceId, HRESULT deploymentErrorExtendedHResult, const wchar_t * deploymentErrorText, _GUID deploymentErrorActivityId, bool useExistingPackageIfHigherVersion) Line 58	C++
 	[Inline Frame] Microsoft.WindowsAppRuntime.dll!Initialize_StopSuccessActivity(WindowsAppRuntime::Deployment::Activity::Context &) Line 33	C++
>	Microsoft.WindowsAppRuntime.dll!winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::implementation::DeploymentManager::_Initialize(WindowsAppRuntime::Deployment::Activity::Context & initializeActivityContext, const winrt::hstring & packageFullName, const winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentInitializeOptions & deploymentInitializeOptions, bool isRepair) Line 260	C++
 	Microsoft.WindowsAppRuntime.dll!winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::implementation::DeploymentManager::Initialize(const winrt::hstring & packageFullName, const winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentInitializeOptions & deploymentInitializeOptions, bool isRepair) Line 195	C++
 	Microsoft.WindowsAppRuntime.dll!winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::implementation::DeploymentManager::Initialize(const winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentInitializeOptions & deploymentInitializeOptions) Line 67	C++
 	[Inline Frame] Microsoft.WindowsAppRuntime.dll!winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::implementation::DeploymentManager::Initialize() Line 61	C++
 	[Inline Frame] Microsoft.WindowsAppRuntime.dll!winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::factory_implementation::DeploymentManagerT<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::factory_implementation::DeploymentManager,winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::implementation::DeploymentManager>::Initialize() Line 22	C++
 	Microsoft.WindowsAppRuntime.dll!winrt::impl::produce<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::factory_implementation::DeploymentManager,winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentManagerStatics>::Initialize(void * * result) Line 200	C++
 	[Managed to Native Transition]	
 	Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll!ABI.Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IDeploymentManagerStaticsMethods.Initialize(WinRT.IObjectReference _obj) Line 791	C#
 	Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll!Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManager.Initialize() Line 178	C#
 	WinAppSdk18InitializeBug.dll!WinAppSdk18InitializeBug.App.App() Line 40	C#
 	WinAppSdk18InitializeBug.dll!WinAppSdk18InitializeBug.Program.Main.AnonymousMethod__0_0(Microsoft.UI.Xaml.ApplicationInitializationCallbackParams p) Line 29	C#
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.ApplicationInitializationCallback.Do_Abi_Invoke(nint thisPtr, nint p) Line 12366	C#
 	[Native to Managed Transition]	
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkApplication::StartDesktop() Line 221	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!DirectUI::FrameworkApplicationFactory::StartImpl(ABI::Microsoft::UI::Xaml::IApplicationInitializationCallback *) Line 183	C++
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkApplicationFactory::Start(ABI::Microsoft::UI::Xaml::IApplicationInitializationCallback * pCallback) Line 843	C++
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference _obj, Microsoft.UI.Xaml.ApplicationInitializationCallback callback) Line 14713	C#
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback callback) Line 318	C#
 	WinAppSdk18InitializeBug.dll!WinAppSdk18InitializeBug.Program.Main(string[] args) Line 26	C#
 	[Native to Managed Transition]	
 	[Inline Frame] hostpolicy.dll!coreclr_t::execute_assembly(int managed_assembly_path, const char * *) Line 109	C++
 	hostpolicy.dll!run_app_for_context(const hostpolicy_context_t & context, int argc, const wchar_t * * argv) Line 256	C++
 	hostpolicy.dll!run_app(const int argc, const wchar_t * * argv) Line 285	C++
 	hostpolicy.dll!corehost_main(const int argc, const wchar_t * * argv) Line 426	C++
 	hostfxr.dll!execute_app(const std::wstring & impl_dll_dir, corehost_init_t * init, const int argc, const wchar_t * * argv) Line 145	C++
 	hostfxr.dll!`anonymous namespace'::read_config_and_execute(const std::wstring & host_command, const host_startup_info_t & host_info, const std::wstring & app_candidate, const std::unordered_map<enum known_options,std::vector<std::wstring,std::allocator<std::wstring>>,known_options_hash,std::equal_to<enum known_options>,std::allocator<std::pair<enum known_options const ,std::vector<std::wstring,std::allocator<std::wstring>>>>> & opts, int new_argc, const wchar_t * * new_argv, host_mode_t mode, const bool is_sdk_command, wchar_t * out_buffer, int buffer_size, int * required_buffer_size) Line 532	C++
 	hostfxr.dll!fx_muxer_t::handle_exec_host_command(const std::wstring & host_command, const host_startup_info_t & host_info, const std::wstring & app_candidate, const std::unordered_map<enum known_options,std::vector<std::wstring,std::allocator<std::wstring>>,known_options_hash,std::equal_to<enum known_options>,std::allocator<std::pair<enum known_options const ,std::vector<std::wstring,std::allocator<std::wstring>>>>> & opts, int argc, const wchar_t * * argv, int argoff, host_mode_t mode, const bool is_sdk_command, wchar_t * result_buffer, int buffer_size, int * required_buffer_size) Line 1007	C++
 	hostfxr.dll!fx_muxer_t::execute(const std::wstring host_command, const int argc, const wchar_t * * argv, const host_startup_info_t & host_info, wchar_t * result_buffer, int buffer_size, int * required_buffer_size) Line 578	C++
 	hostfxr.dll!hostfxr_main_startupinfo(const int argc, const wchar_t * * argv, const wchar_t * host_path, const wchar_t * dotnet_root, const wchar_t * app_path) Line 62	C++
 	WinAppSdk18InitializeBug.exe!exe_start(const int argc, const wchar_t * * argv) Line 240	C++
 	WinAppSdk18InitializeBug.exe!wmain(const int argc, const wchar_t * * argv) Line 311	C++
 	[Inline Frame] WinAppSdk18InitializeBug.exe!invoke_main() Line 90	C++
 	WinAppSdk18InitializeBug.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
```

### Steps to reproduce the bug

1. Create blank WinUI 3 C# app from Visual Studio template
2. Update Windows App SDK NuGet to 1.8.250702007-experimental4
3. Add `DeploymentManager.Initialize();` to `App.xaml.cs` constructor
4. (For seeing detailed crash info, enable native debugging)
5. Build and run the app

### Expected behavior

No crash.

### Screenshots

_No response_

### NuGet package version

Windows App SDK 1.8 Experimental 4: 1.8.250702007-experimental4

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 24H2 (26100, June 2025 Update)

### IDE

Visual Studio 2022

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ssparach**
## Summary
This pull request resolves an application crash/fail fast occurring during the call to `DeploymentManager.Initialize()`, as reported in issue #5605. The DeploymentManager initialize is expected to only be called once, but in the case of the issue repro, it is getting called twice. This is because of the explicit call to initialize in the constructor and the default property value for WindowsAppSdkDeploymentManagerInitialize being set to true.

The change corrects error handling in `DeploymentManager.Initialize()` to prevent crash scenarios/fail fast. Instead an exception is thrown that is explanatory on the issue and can be handled by the application. 

## Testing
- The change was tested manually in the repro scenario to observe the new exception being thrown
image
- Pipeline Runs 

-----------------------------------------------------------------------------------------------------------------------------------------
A microsoft employee must use /azp run to validate using the pipelines below.

WARNING:
Comments made by azure-pipelines bot maybe inaccurate.
Please see pipeline link to verify that the build is being ran.

For status checks on the main branch, please use TransportPackage-Foundation-PR
(https://microsoft.visualstudio.com/ProjectReunion/_build?definitionId=81063&_a=summary)
and run the build against your PR branch with the default parameters.

### CODE REVIEW

File: dev/Deployment/DeploymentManager.cpp [hunk 1]
```diff
@@ -48,6 +48,7 @@ inline void Initialize_StopSuccessActivity(
 
 namespace winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::implementation
 {
+    static bool isInitializedByDefault{ false };
```
Comment (Scottj1s) [inline dev/Deployment/DeploymentManager.cpp]: can we rename for slight clarity?
```suggestion
    static bool isAutoInitialized{ false };
```

File: dev/Deployment/DeploymentManager.cpp [hunk 2]
```diff
@@ -164,6 +165,14 @@ namespace winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::implem
         winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentInitializeOptions const& deploymentInitializeOptions,
         bool isRepair)
     {
+        if (isInitializedByDefault)
+        {
+            HRESULT hr = HRESULT_FROM_WIN32(E_UNEXPECTED);
+            winrt::hstring message = L"DeploymentManager can only be initialized once and has already been initialized by default. "
+                L"If you would like to explicitly initialize, add <WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize> to your .csproj file.";
```
Comment (Scottj1s) [inline dev/Deployment/DeploymentManager.cpp]: The error could be from either source - so maybe a more neutral suggestion
```suggestion
                L"Please either remove your explicit initialization call, or disable auto-initialization by adding <WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize> to your .csproj file.";
```

File: dev/Deployment/DeploymentManager.cpp (hunk 1 above)
Comment (ssparach) [reply dev/Deployment/DeploymentManager.cpp]: Changed name throughout file in latest commit. Thanks!
